version: '3.3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
volumes:
  my-db: